/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "s21_calc.h"
#define MAX 256

START_TEST(add_1) {
char str[MAX] = "2+3";
double x = 0;
double check;
double check_origin = 2+3;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(add_2) {
char str[MAX] = "2.2+3.3";
double x = 0;
double check;
double check_origin = 2.2+3.3;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(add_3) {
char str[MAX] = "1.23456789+0.987654";
double x = 0;
double check;
double check_origin = 1.23456789+0.987654;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(add_4) {
char str[MAX] = "1.23456789+x";
double x = 0.987654321;
double check;
double check_origin = 1.23456789+0.987654321;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sub_1) {
char str[MAX] = "3-2";
double x = 0;
double check;
double check_origin = 3-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sub_2) {
char str[MAX] = "3.3-2.2";
double x = 0;
double check;
double check_origin = 3.3-2.2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sub_3) {
char str[MAX] = "1.23456789-0.987654";
double x = 0;
double check;
double check_origin = 1.23456789-0.987654;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sub_4) {
char str[MAX] = "1.23456789-x";
double x = 0.987654;
double check;
double check_origin = 1.23456789-0.987654;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mul_1) {
char str[MAX] = "3*2";
double x = 0;
double check;
double check_origin = 3*2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mul_2) {
char str[MAX] = "3.3*2.2";
double x = 0;
double check;
double check_origin = 3.3*2.2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mul_3) {
char str[MAX] = "1.23456789*0.987654";
double x = 0;
double check;
double check_origin = 1.23456789*0.987654;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mul_4) {
char str[MAX] = "1.23456789*x";
double x = 0.987654;
double check;
double check_origin = 1.23456789*0.987654;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(div_1) {
char str[MAX] = "3/2";
double x = 0;
double check;
double check_origin = 3.0/2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(div_2) {
char str[MAX] = "3.3/2.2";
double x = 0;
double check;
double check_origin = 3.3/2.2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(div_3) {
char str[MAX] = "1.23456789/0.987654";
double x = 0;
double check;
double check_origin = 1.23456789/0.987654;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(div_4) {
char str[MAX] = "1.23456789/x";
double x = 0.987654;
double check;
double check_origin = 1.23456789/0.987654;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(pow_1) {
char str[MAX] = "3^2";
double x = 0;
double check;
double check_origin = pow(3, 2);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(pow_2) {
char str[MAX] = "3.3^2.2";
double x = 0;
double check;
double check_origin = pow(3.3, 2.2);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(pow_3) {
char str[MAX] = "1.23456789^0.987654";
double x = 0;
double check;
double check_origin = pow(1.23456789, 0.987654);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(pow_4) {
char str[MAX] = "1.23456789^x";
double x = 0.987654;
double check;
double check_origin = pow(1.23456789, 0.987654);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mod_1) {
char str[MAX] = "3mod2";
double x = 0;
double check;
double check_origin = fmod(3, 2);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mod_2) {
char str[MAX] = "3.3mod2.2";
double x = 0;
double check;
double check_origin = fmod(3.3, 2.2);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mod_3) {
char str[MAX] = "1.23456789mod0.987654";
double x = 0;
double check;
double check_origin = fmod(1.23456789, 0.987654);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(mod_4) {
char str[MAX] = "1.23456789modx";
double x = 0.987654;
double check;
double check_origin = fmod(1.23456789, 0.987654);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_1) {
char str[MAX] = "-1.23456789";
double x = 0;
double check;
double check_origin = -1.23456789;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_2) {
char str[MAX] = "+1.23456789";
double x = 0;
double check;
double check_origin = +1.23456789;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_3) {
char str[MAX] = "+x";
double x = 1.23456789;
double check;
double check_origin = +1.23456789;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_4) {
char str[MAX] = "-x";
double x = 1.23456789;
double check;
double check_origin = -1.23456789;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(cos_1) {
char str[MAX] = "cos(1)";
double x = 0;
double check;
double check_origin = cos(1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(cos_2) {
char str[MAX] = "2*cos(2*x)-2";
double x = 1;
double check;
double check_origin = 2*cos(2*1)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sin_1) {
char str[MAX] = "sin(1)";
double x = 0;
double check;
double check_origin = sin(1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sin_2) {
char str[MAX] = "2*sin(2*x)-2";
double x = 1;
double check;
double check_origin = 2*sin(2*1)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(tan_1) {
char str[MAX] = "tan(1)";
double x = 0;
double check;
double check_origin = tan(1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(tan_2) {
char str[MAX] = "2*tan(2*x)-2";
double x = 1;
double check;
double check_origin = 2*tan(2*1)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(acos_1) {
char str[MAX] = "acos(0.5)";
double x = 0;
double check;
double check_origin = acos(0.5);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(acos_2) {
char str[MAX] = "2*acos(x)-2";
double x = 0.5;
double check;
double check_origin = 2*acos(0.5)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(asin_1) {
char str[MAX] = "asin(0.5)";
double x = 0;
double check;
double check_origin = asin(0.5);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(asin_2) {
char str[MAX] = "2*asin(x)-2";
double x = 0.5;
double check;
double check_origin = 2*asin(0.5)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(atan_1) {
char str[MAX] = "atan(1)";
double x = 0;
double check;
double check_origin = atan(1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(atan_2) {
char str[MAX] = "2*atan(2*x)-2";
double x = 1;
double check;
double check_origin = 2*atan(2*1)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sqrt_1) {
char str[MAX] = "sqrt(1)";
double x = 0;
double check;
double check_origin = sqrt(1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(sqrt_2) {
char str[MAX] = "2*sqrt(2*x)-2";
double x = 1;
double check;
double check_origin = 2*sqrt(2*1)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_deg_1) {
char str[MAX] = "-5^-1";
double x = 0;
double check;
double check_origin = pow(-5, -1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_deg_2) {
char str[MAX] = "-5^x";
double x = -1;
double check;
double check_origin = pow(-5, -1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_deg_3) {
char str[MAX] = "-5^+1";
double x = 0;
double check;
double check_origin = pow(-5, +1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(un_deg_4) {
char str[MAX] = "-5^+x";
double x = -1;
double check;
double check_origin = pow(-5, +(-1));
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(diff_1) {
char str[MAX] = "(-cos(-2^4)^2)*5/3+(ln(sqrt(25))+-(sin(-4)))";
double x = 0;
double check;
double check_origin = -0.6758840499614303;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(ln_1) {
char str[MAX] = "ln(1)";
double x = 0;
double check;
double check_origin = log(1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(ln_2) {
char str[MAX] = "2*ln(2*x)-2";
double x = 1;
double check;
double check_origin = 2*log(2*1)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(log_1) {
char str[MAX] = "log(1)";
double x = 0;
double check;
double check_origin = log10(1);
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(log_2) {
char str[MAX] = "2*log(2*x)-2";
double x = 1;
double check;
double check_origin = 2*log10(2*1)-2;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(diff_2) {
char str[MAX] = "(5+10/1.1+sin(1))/sqrt(2)";
double x = 0;
double check;
double check_origin = 10.558787210794447;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(diff_3) {
char str[MAX] = "atan(x+2)-cos(1+x/(3-x))^(2*x^(1/2))";
double x = 0.1;
double check;
double check_origin = 0.472383675629815421127129;
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(calc_cred_annu_1) {
double ost_kr = 100000;
int srok = 12;
double pr_stav = 12;
int x = 11;
double plat_mes, plat_dolg, plat_proc, vse_dolg, vse_proc;
double check_origin = 8884.88;
calc_cred_annu(ost_kr, srok, pr_stav, x,
&plat_mes, &plat_dolg, &plat_proc, &vse_dolg, &vse_proc);
ck_assert_double_eq_tol(plat_mes, check_origin, 1e-7);
}
END_TEST

START_TEST(calc_cred_diff_1) {
double ost_kr = 100000;
int srok = 12;
double pr_stav = 12;
int x = 11;
double plat_mes, plat_dolg, plat_proc, vse_dolg, vse_proc;
double check_origin = 8333.33;
calc_cred_diff(ost_kr, srok, pr_stav, x,
&plat_mes, &plat_dolg, &plat_proc, &vse_dolg, &vse_proc);
ck_assert_double_eq_tol(plat_dolg, check_origin, 1e-7);
}
END_TEST

START_TEST(diff_4) {
char str[MAX] = "-(-acos(0.5))";
double x = 0.1;
double check;
double check_origin = -(-acos(0.5));
calc(str, x, &check);
ck_assert_double_eq_tol(check, check_origin, 1e-7);
}
END_TEST

START_TEST(err_1) {
int err;
char str[MAX] = "x2";
double x = 1;
double check;
double check_origin = 1;
err = calc(str, x, &check);
ck_assert_double_eq_tol(err, check_origin, 1e-7);
}
END_TEST

START_TEST(err_2) {
int err;
char str[MAX] = "*adg";
double x = 1;
double check;
double check_origin = 1;
err = calc(str, x, &check);
ck_assert_double_eq_tol(err, check_origin, 1e-7);
}
END_TEST

START_TEST(err_3) {
int err;
char str[MAX] = "X*Y";
double x = 1;
double check;
double check_origin = 1;
err = calc(str, x, &check);
ck_assert_double_eq_tol(err, check_origin, 1e-7);
}
END_TEST

START_TEST(err_4) {
int err;
char str[MAX] = "----Xmod)";
double x = 1;
double check;
double check_origin = 1;
err = calc(str, x, &check);
ck_assert_double_eq_tol(err, check_origin, 1e-7);
}
END_TEST

START_TEST(err_5) {
int err;
char str[MAX] = "sin(1)cos(1)";
double x = 1;
double check;
double check_origin = 1;
err = calc(str, x, &check);
ck_assert_double_eq_tol(err, check_origin, 1e-7);
}
END_TEST

START_TEST(err_6) {
int err;
char str[MAX] = "5*)";
double x = 1;
double check;
double check_origin = 1;
err = calc(str, x, &check);
ck_assert_double_eq_tol(err, check_origin, 1e-7);
}
END_TEST

START_TEST(err_7) {
int err;
char str[MAX] = "5mod*5";
double x = 1;
double check;
double check_origin = 1;
err = calc(str, x, &check);
ck_assert_double_eq_tol(err, check_origin, 1e-7);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, add_1);
    tcase_add_test(tc1_1, add_2);
    tcase_add_test(tc1_1, add_3);
    tcase_add_test(tc1_1, add_4);
    tcase_add_test(tc1_1, sub_1);
    tcase_add_test(tc1_1, sub_2);
    tcase_add_test(tc1_1, sub_3);
    tcase_add_test(tc1_1, sub_4);
    tcase_add_test(tc1_1, mul_1);
    tcase_add_test(tc1_1, mul_2);
    tcase_add_test(tc1_1, mul_3);
    tcase_add_test(tc1_1, mul_4);
    tcase_add_test(tc1_1, div_1);
    tcase_add_test(tc1_1, div_2);
    tcase_add_test(tc1_1, div_3);
    tcase_add_test(tc1_1, div_4);
    tcase_add_test(tc1_1, pow_1);
    tcase_add_test(tc1_1, pow_2);
    tcase_add_test(tc1_1, pow_3);
    tcase_add_test(tc1_1, pow_4);
    tcase_add_test(tc1_1, mod_1);
    tcase_add_test(tc1_1, mod_2);
    tcase_add_test(tc1_1, mod_3);
    tcase_add_test(tc1_1, mod_4);
    tcase_add_test(tc1_1, un_1);
    tcase_add_test(tc1_1, un_2);
    tcase_add_test(tc1_1, un_3);
    tcase_add_test(tc1_1, un_4);
    tcase_add_test(tc1_1, cos_1);
    tcase_add_test(tc1_1, cos_2);
    tcase_add_test(tc1_1, sin_1);
    tcase_add_test(tc1_1, sin_2);
    tcase_add_test(tc1_1, tan_1);
    tcase_add_test(tc1_1, tan_2);
    tcase_add_test(tc1_1, acos_1);
    tcase_add_test(tc1_1, acos_2);
    tcase_add_test(tc1_1, asin_1);
    tcase_add_test(tc1_1, asin_2);
    tcase_add_test(tc1_1, atan_1);
    tcase_add_test(tc1_1, atan_2);
    tcase_add_test(tc1_1, sqrt_1);
    tcase_add_test(tc1_1, sqrt_2);
    tcase_add_test(tc1_1, un_deg_1);
    tcase_add_test(tc1_1, un_deg_2);
    tcase_add_test(tc1_1, un_deg_3);
    tcase_add_test(tc1_1, un_deg_4);
    tcase_add_test(tc1_1, diff_1);
    tcase_add_test(tc1_1, ln_1);
    tcase_add_test(tc1_1, ln_2);
    tcase_add_test(tc1_1, log_1);
    tcase_add_test(tc1_1, log_2);
    tcase_add_test(tc1_1, diff_2);
    tcase_add_test(tc1_1, diff_3);
    tcase_add_test(tc1_1, calc_cred_annu_1);
    tcase_add_test(tc1_1, calc_cred_diff_1);
    tcase_add_test(tc1_1, diff_4);
    tcase_add_test(tc1_1, err_1);
    tcase_add_test(tc1_1, err_2);
    tcase_add_test(tc1_1, err_3);
    tcase_add_test(tc1_1, err_4);
    tcase_add_test(tc1_1, err_5);
    tcase_add_test(tc1_1, err_6);
    tcase_add_test(tc1_1, err_7);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
